name: my action

on:
  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
